WITH user_info_2021 AS (
  SELECT USER_ID
  FROM USER_INFO
  WHERE YEAR(JOINED) = 2021
), online_sale_2021 AS (
  SELECT 
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT os.USER_ID) AS PUCHASED_USERS
  FROM ONLINE_SALE os
  JOIN user_info_2021 ui ON os.USER_ID = ui.USER_ID
  GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
)
SELECT
  os.YEAR,
  os.MONTH,
  os.PUCHASED_USERS,
  ROUND(os.PUCHASED_USERS / (SELECT COUNT(*) FROM user_info_2021), 1) AS PUCHASED_RATIO
FROM online_sale_2021 os
ORDER BY os.YEAR, os.MONTH;